# ───────────────────────────────
# Chart / Naming
# ───────────────────────────────
nameOverride: "" 
fullnameOverride: ""

# ───────────────────────────────
# Deployment / Scaling
# ───────────────────────────────
# TODO: Change this to HPA
replicaCount: 1

# ───────────────────────────────
# Image & Registry
# ───────────────────────────────
image:
  repository: docker.io/frantkich/devops-training-backend-app
  pullPolicy: Always
  # TODO: Change this to fix version
  tag: latest
imagePullSecrets: []

# ───────────────────────────────
# Application Configuration
# ───────────────────────────────
app:
  env:
    # TODO: Change this to prod
    - name: FLASK_DEBUG
      value: "1"
  args:
    - "--workers=2"
    - "--bind=0.0.0.0:8000"
    - "main:app"

# ───────────────────────────────
# Pod Configuration
# ───────────────────────────────

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"
  # readOnlyRootFilesystem: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http-python
readinessProbe:
  httpGet:
    path: /healthz
    port: http-python

volumes: []
volumeMounts: []

# ───────────────────────────────
# Networking
# ───────────────────────────────
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
  hosts:
    - host: devops-training.api.frantkich.fr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - devops-training.api.frantkich.fr
      secretName: devops-training-backend-tls

# ───────────────────────────────
# DB
# ───────────────────────────────
mariadb:
  enabled: true
  auth:
    database: devops_training
    rootPassword: mariadb-root-password
  persistence:
    size: 1Gi
  volumePermissions:
    enabled: true