# ───────────────────────────────
# Chart / Naming
# ───────────────────────────────
nameOverride: "" 
fullnameOverride: ""

# ───────────────────────────────
# Deployment / Scaling
# ───────────────────────────────
# TODO: Change this to HPA
replicaCount: 1

# ───────────────────────────────
# Image & Registry
# ───────────────────────────────
image:
  repository: docker.io/frantkich/devops-training-backend-app
  pullPolicy: Always
  # TODO: Change this to fix version
  tag: latest
imagePullSecrets: []

# ───────────────────────────────
# Application Configuration
# ───────────────────────────────
app:
  env:
    # TODO: Change this to prod
    - name: FLASK_DEBUG
      value: "1"
  args:
    - "--workers=2"
    - "--bind=0.0.0.0:8000"
    - "main:app"

# ───────────────────────────────
# Pod Configuration
# ───────────────────────────────

podAnnotations: {}
podLabels:
  app: backend

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: "RuntimeDefault"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: http-python
readinessProbe:
  httpGet:
    path: /healthz
    port: http-python

volumes:
  - name: tmp
    emptyDir: {}
volumeMounts:
  - name: tmp
    mountPath: /tmp

# ───────────────────────────────
# Networking
# ───────────────────────────────
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
  hosts:
    - host: devops-training.api.frantkich.fr
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
      - devops-training.api.frantkich.fr
      secretName: devops-training-backend-tls

# ───────────────────────────────
# DB
# ───────────────────────────────
mariadb:
  enabled: true
  commonLabels:
    app: db

  auth:
    database: devops_training
    username: appuser
    existingSecret: mariadb-secret
    
  primary:
    podSecurityContext:
      fsGroup: 1001
      fsGroupChangePolicy: Always

    containerSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

    persistence:
      enabled: true
      size: 1Gi

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi

  volumePermissions:
    enabled: false
