FROM python:3.13-alpine

WORKDIR /code
COPY requirements.txt /code
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

EXPOSE 8000

COPY . .

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "-t", "0", "main:app"]